name: build-website

on:
  workflow_call:

jobs:
  build-application:
    name: Build application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Build publishable website
      run: |
        dotnet publish --configuration Release
      working-directory: ./src/HelloWorldWebApp/wwwroot

    - name: Zip publishable website
      run: |
        zip -r publish.zip .
      working-directory: ./src/HelloWorldWebApp/wwwroot

    - name: Upload website as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: website
        path: ./src/ToyCompany/HelloWorldWebApp/wwwroot/publish.zip