name: Build application

on:
  workflow_dispatch:
  workflow_call:

env:
  AZURE_WEBAPP_NAME: website-p6oa4jx6vfo42
  AZURE_WEBAPP_PACKAGE_PATH: 'src/HelloWorldWebApp/publish/HelloWorldWebApp'
  DOTNET_VERSION: '8.0.x'
  SOLUTION_PATH: 'src/HelloWorldWebApp/HelloWorldWebApp.sln'
  PROJECT_PATH: 'src/HelloWorldWebApp/HelloWorldWebApp.csproj'

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}