name: Build application

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./src/HelloWorldWebApp/HelloWorldWebApp.sln

    - name: Build
      run: dotnet build ./src/HelloWorldWebApp/HelloWorldWebApp.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./src/HelloWorldWebApp/HelloWorldWebApp.sln --configuration Release --no-build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorldWebApp
        path: src/HelloWorldWebApp/bin/Release/net8.0/publish