name: deploy-end-to-end
concurrency: deployment

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:

    # Build the application
    build:
      uses: ./.github/workflows/build.yml

    # Lint the Bicep file
    lint:
      uses: ./.github/workflows/lint.yml

    # Deploy to the test environment
    deploy-test:
      uses: ./.github/workflows/deploy.yml
      needs: [build, lint]
      with:
        environmentType: Test
        resourceGroupName: rg-Test
      secrets:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Deploy to the production environment
    deploy-production:
      uses: ./.github/workflows/deploy.yml
      needs:
        - lint
        - build
        - deploy-test    
      with:
        environmentType: Production
        resourceGroupName: rg-Production
      secrets:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PRODUCTION }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
